CREATE TABLE `raw_clean_google_map_data` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `raw_id` bigint NOT NULL COMMENT 'Refers to validation_raw_google_map.raw_id',
  `signature_hash` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` text COLLATE utf8mb4_unicode_ci,
  `website` text COLLATE utf8mb4_unicode_ci,
  `phone_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviews_count` int DEFAULT '0',
  `reviews_avg` float DEFAULT '0',
  `category` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subcategory` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `area` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `validation_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'VALID',
  `cleaning_status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'CLEANED',
  `missing_fields` text COLLATE utf8mb4_unicode_ci,
  `invalid_format_fields` text COLLATE utf8mb4_unicode_ci,
  `duplicate_reason` text COLLATE utf8mb4_unicode_ci,
  `processed_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `raw_id` (`raw_id`),
  UNIQUE KEY `idx_raw_id` (`raw_id`),
  UNIQUE KEY `idx_composite_dedup` (`name`(100),`phone_number`,`city`(50),`address`(100)),
  KEY `idx_sig_hash` (`signature_hash`)
) ENGINE=InnoDB AUTO_INCREMENT=2989196 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
